name: 'Backend Continuous Integration'

env:
  REACT_APP_MOVIE_API_URL: 'http://localhost:5000'
  REPO_NAME: 'backend'
  IMAGE_TAG: ${{ github.sha }}

on:
  workflow_dispatch:
  push:
    branches:
      - 'main'
    paths:
      - 'starter/backend/**'

jobs:
  lint:
    uses: ./.github/workflows/backend-common.yml

  test:
    uses: ./.github/workflows/backend-common.yml

  build:
    name: 'Build code'
    runs-on: ubuntu-latest
    needs:
      - lint
      - test

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'
          cache: 'pipenv'

      - name: Install pipenv
        run: curl https://raw.githubusercontent.com/pypa/pipenv/master/get-pipenv.py | python

      - name: Build docker image
        uses: docker/build-push-action@v6
        with:
          context: starter/backend
          push: false
          tags: "${{ env.REPO_NAME }}:${{ env.IMAGE_TAG }}"
