name: 'Movie picture frontend deploy'

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  lint:
    name: 'Lint code'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run lint
        run: |
          cd starter/frontend/src
          npm ci
          npm run lint

  test:
    name: 'Test code'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: 18

      - name: Run tests 
        run: |
          cd starter/frontend/src
          npm ci
          npm test
